### ISSUE TITLE
Черный экран

### ISSUE THREAD

**Issue by Raiva136** [Kirill-Lekhov/gbfr-russifier#2]
После установки перевода просто черный экран. Версия игры из стима 1.3.2

**Comment by Kirill-Lekhov** [comment]
Здравствуйте!

Спасибо за обратную связь! Пожалуйста, попробуйте эту версию.

https://github.com/Kirill-Lekhov/gbfr-russifier/releases/tag/v0.1.2

**Comment by Raiva136** [comment]
Помогло, теперь работает Русский язык в игре. Спасибо за решение проблемы.
